#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AdvancedMap.Droid.Resource", IsApplication=true)]

namespace AdvancedMap.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int direction_down = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int direction_up = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int direction_upthenleft = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int direction_upthenright = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int marker = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int olmarker = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MapListCell = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MapListView = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int mapView = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int package_action = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int package_item_row = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int package_name = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int package_status = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int textViewMessage = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int List = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MainGPS = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int package_item_row = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
