
version: 1.0.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

branches:
  only:
  - master

before_build:
  - nuget restore

build:
  project: mobile_dotnet_samples.sln
  verbosity: minimal
